In [1]:
a=2
print(a)


2


In [2]:
type(a)

int

In [3]:
for i in range(1,15):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [4]:
import numpy as np


In [6]:
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [7]:
type(arr1)

numpy.ndarray

In [8]:
arr1.dtype()

TypeError: 'numpy.dtypes.Int32DType' object is not callable

In [9]:
arr1.dtype

dtype('int32')

In [10]:
arr1.shape

(4,)

In [11]:
arr1.size

4

In [12]:
len(arr1)

4

In [13]:
arr2 = np.array([5,6,7,8])
arr2

array([5, 6, 7, 8])

In [14]:
arr1+arr2

array([ 6,  8, 10, 12])

In [15]:
type(arr2)

numpy.ndarray

In [16]:
arr3 = np.arange(12)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
arr3.dtype

dtype('int32')

In [18]:
arr3.size

12

In [23]:
arr3.astype

<function ndarray.astype>

In [21]:
arr3.argmax()

11

In [24]:
arr3.argmin()

0

In [25]:
arr3.argsort()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int64)

In [26]:
arr3.argmax()

11

In [28]:
arr3.dtype

dtype('int32')

In [29]:
arr4 = np.arange(14)
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [30]:
#import pandas as pd

In [31]:
# Import necessary libraries
import numpy as np
import pandas as pd
# Load the dataset (replace 'your_dataset.csv' with your file path or URL)
df = pd.read_csv('your_dataset.csv')

# 1. Basic Inspection

# View the first few rows of the dataset
print("First 5 rows of the dataset:")
print(df.head())

# Check the shape of the dataset (number of rows and columns)
print("\nShape of the dataset:")
print(df.shape)

# Get information about data types and non-null values
print("\nInfo of the dataset:")
df.info()

# Get summary statistics for numerical columns
print("\nSummary statistics:")
print(df.describe())

# 2. Handling Missing Values

# Check for missing values
print("\nMissing values per column:")
print(df.isnull().sum())

# Option 1: Drop rows with missing values
df_cleaned = df.dropna()

# Option 2: Fill missing values (example: filling with mean of the column)
df_filled = df.fillna(df.mean())

# 3. Data Selection and Filtering

# Selecting a specific column
column_data = df['column_name']

# Selecting multiple columns
multiple_columns = df[['column1', 'column2']]

# Filtering rows based on condition
filtered_data = df[df['column_name'] > some_value]

# 4. Data Manipulation

# Creating a new column (example: calculating BMI)
df['BMI'] = df['weight'] / (df['height'] ** 2)

# Renaming columns
df.rename(columns={'old_name': 'new_name'}, inplace=True)

# Dropping columns
df_dropped = df.drop(['unnecessary_column'], axis=1)

# 5. Grouping and Aggregation

# Grouping data by a column and calculating the mean
grouped_data = df.groupby('group_column').mean()

# 6. Sorting Data

# Sorting data by a specific column
df_sorted = df.sort_values(by='column_name', ascending=False)

# 7. Merging and Joining DataFrames

# Merge two DataFrames based on a common column
df1 = pd.DataFrame({'key': ['A', 'B', 'C'], 'value1': [1, 2, 3]})
df2 = pd.DataFrame({'key': ['A', 'B', 'D'], 'value2': [4, 5, 6]})

df_merged = pd.merge(df1, df2, on='key', how='inner')  # how can be 'inner', 'outer', 'left', 'right'

# 8. Exporting the Data

# Save the DataFrame to a CSV file
df.to_csv('output.csv', index=False)

# Save the DataFrame to an Excel file
df.to_excel('output.xlsx', index=False)

# 9. Plotting Data (requires Matplotlib or Seaborn)

import matplotlib.pyplot as plt

# Example: Plot a histogram of a column
df['column_name'].hist(bins=20)
plt.show()



FileNotFoundError: [Errno 2] No such file or directory: 'your_dataset.csv'

In [32]:
# Import Pandas
import pandas as pd

# Load a CSV file
df = pd.read_csv('your_dataset.csv')

# 1. Basic Inspection

# Display the first few rows of the data
print(df.head())

# Check the shape of the data (rows, columns)
print(df.shape)

# Check data types and if there are missing values
print(df.info())

# Summary statistics for numerical columns
print(df.describe())

# 2. Handling Missing Values

# Fill missing values with 0
df.fillna(0, inplace=True)

# 3. Selecting Data

# Select a column
print(df['column_name'])

# Filter rows where a column value is greater than a certain number
filtered_data = df[df['column_name'] > 10]
print(filtered_data)

# 4. Sorting

# Sort data by a specific column
df_sorted = df.sort_values(by='column_name')
print(df_sorted)

# 5. Export Data

# Save DataFrame to a new CSV file
df.to_csv('output.csv', index=False)


FileNotFoundError: [Errno 2] No such file or directory: 'your_dataset.csv'

In [37]:
import numpy as np
import pandas as pd
df  = pd.DataFrame(
    
    
print(df)

SyntaxError: unterminated string literal (detected at line 4) (2794132207.py, line 4)

In [38]:
# Import Pandas
import pandas as pd

# 1. Creating a DataFrame

# Define data as a dictionary
data = {
    'Name': ['John', 'Sara', 'Mike', 'Emma'],
    'Age': [28, 22, 32, 29],
    'City': ['New York', 'Paris', 'London', 'Tokyo'],
    'Salary': [70000, 65000, 80000, 75000]
}

# Create DataFrame from the dictionary
df = pd.DataFrame(data)

# 2. Display DataFrame

print("DataFrame:")
print(df)

# 3. Basic Operations

# Display column names
print("\nColumn names:")
print(df.columns)

# Access a specific column (e.g., 'Name')
print("\nNames column:")
print(df['Name'])

# Add a new column (e.g., 'Bonus')
df['Bonus'] = df['Salary'] * 0.10
print("\nDataFrame with Bonus column added:")
print(df)

# 4. Filter rows based on a condition (e.g., Age > 25)
filtered_df = df[df['Age'] > 25]
print("\nFiltered DataFrame (Age > 25):")
print(filtered_df)

# 5. Sorting

# Sort DataFrame by Salary in descending order
df_sorted = df.sort_values(by='Salary', ascending=False)
print("\nDataFrame sorted by Salary (descending):")
print(df_sorted)

# 6. Export the DataFrame to CSV

df.to_csv('employees.csv', index=False)
print("\nDataFrame exported to employees.csv")




DataFrame:
   Name  Age      City  Salary
0  John   28  New York   70000
1  Sara   22     Paris   65000
2  Mike   32    London   80000
3  Emma   29     Tokyo   75000

Column names:
Index(['Name', 'Age', 'City', 'Salary'], dtype='object')

Names column:
0    John
1    Sara
2    Mike
3    Emma
Name: Name, dtype: object

DataFrame with Bonus column added:
   Name  Age      City  Salary   Bonus
0  John   28  New York   70000  7000.0
1  Sara   22     Paris   65000  6500.0
2  Mike   32    London   80000  8000.0
3  Emma   29     Tokyo   75000  7500.0

Filtered DataFrame (Age > 25):
   Name  Age      City  Salary   Bonus
0  John   28  New York   70000  7000.0
2  Mike   32    London   80000  8000.0
3  Emma   29     Tokyo   75000  7500.0

DataFrame sorted by Salary (descending):
   Name  Age      City  Salary   Bonus
2  Mike   32    London   80000  8000.0
3  Emma   29     Tokyo   75000  7500.0
0  John   28  New York   70000  7000.0
1  Sara   22     Paris   65000  6500.0

DataFrame exported to em

In [39]:
import numpy as np
import pandas as pd

In [41]:
df = pd.read_csv('employees.csv')
df

,Name,Age,City,Salary,Bonus
0,John,28,New York,70000,7000.0
1,Sara,22,Paris,65000,6500.0
2,Mike,32,London,80000,8000.0
3,Emma,29,Tokyo,75000,7500.0


In [42]:
type(df)

pandas.core.frame.DataFrame

In [43]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [44]:
df.isnull().sum()

Name      0
Age       0
City      0
Salary    0
Bonus     0
dtype: int64

In [46]:
df.shape

(4, 5)

In [47]:
df.size

20

In [48]:
type(df)

pandas.core.frame.DataFrame

In [49]:
df.count()

Name      4
Age       4
City      4
Salary    4
Bonus     4
dtype: int64

In [51]:
df.corr

<bound method DataFrame.corr of    Name  Age      City  Salary   Bonus
0  John   28  New York   70000  7000.0
1  Sara   22     Paris   65000  6500.0
2  Mike   32    London   80000  8000.0
3  Emma   29     Tokyo   75000  7500.0>

In [52]:
df.columns

Index(['Name', 'Age', 'City', 'Salary', 'Bonus'], dtype='object')

In [ ]:
df.