In [ ]:
import pywhatkit as kit

# Sending a WhatsApp message to a single contact
phone_number = "+919548866926"  # Replace with the recipient's phone number
message = "Hello! This is a test message sent from Python."

# Send a message at a specific time (24-hour format)
kit.sendwhatmsg(phone_number, message, 14, 30)  # Time in (HH, MM) format


In 79963 Seconds WhatsApp will open and after 15 Seconds Message will be Delivered!


In [1]:
import numpy as np

# 1. Creating a 1D NumPy array from a Python list
arr1 = np.array([10, 20, 30, 40, 50])
print("1D Array:", arr1)

# 2. Creating a 2D NumPy array (Matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D Array (Matrix):\n", arr2)

# 3. Creating an array with all zeros
zeros_arr = np.zeros((3, 3))
print("\nArray of Zeros:\n", zeros_arr)

# 4. Creating an array with all ones
ones_arr = np.ones((2, 4))
print("\nArray of Ones:\n", ones_arr)

# 5. Creating an array with a range of values
range_arr = np.arange(0, 10, 2)
print("\nArray with Range of Values (0 to 10 with step 2):", range_arr)

# 6. Creating an array with random values
random_arr = np.random.rand(3, 3)
print("\nRandom Array:\n", random_arr)

# 7. Array operations (addition, multiplication)
arr3 = np.array([1, 2, 3, 4, 5])
arr4 = np.array([5, 4, 3, 2, 1])

# Element-wise addition
add_result = arr3 + arr4
print("\nElement-wise Addition:", add_result)

# Element-wise multiplication
mul_result = arr3 * arr4
print("Element-wise Multiplication:", mul_result)

# 8. Reshaping an array
reshaped_arr = np.reshape(arr1, (5, 1))
print("\nReshaped Array (5 rows, 1 column):\n", reshaped_arr)

# 9. Transposing a 2D array
transposed_arr = np.transpose(arr2)
print("\nTransposed 2D Array:\n", transposed_arr)

# 10. Accessing array elements (indexing and slicing)
print("\nElement at Index 2 in arr1:", arr1[2])
print("Slicing arr1 (index 1 to 3):", arr1[1:4])

# 11. Array broadcasting (adding a scalar to an array)
broadcast_arr = arr1 + 10
print("\nBroadcasting (Adding 10 to arr1):", broadcast_arr)

# 12. Stacking arrays (vertical and horizontal stacking)
arr5 = np.array([1, 2, 3])
arr6 = np.array([4, 5, 6])

# Vertical stacking
vstack_arr = np.vstack((arr5, arr6))
print("\nVertically Stacked Arrays:\n", vstack_arr)

# Horizontal stacking
hstack_arr = np.hstack((arr5, arr6))
print("\nHorizontally Stacked Arrays:", hstack_arr)


1D Array: [10 20 30 40 50]

2D Array (Matrix):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Array of Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Array of Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Array with Range of Values (0 to 10 with step 2): [0 2 4 6 8]

Random Array:
 [[0.48053528 0.15055144 0.95843888]
 [0.81477801 0.73740452 0.55444714]
 [0.54645802 0.45602362 0.06967951]]

Element-wise Addition: [6 6 6 6 6]
Element-wise Multiplication: [5 8 9 8 5]

Reshaped Array (5 rows, 1 column):
 [[10]
 [20]
 [30]
 [40]
 [50]]

Transposed 2D Array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]

Element at Index 2 in arr1: 30
Slicing arr1 (index 1 to 3): [20 30 40]

Broadcasting (Adding 10 to arr1): [20 30 40 50 60]

Vertically Stacked Arrays:
 [[1 2 3]
 [4 5 6]]

Horizontally Stacked Arrays: [1 2 3 4 5 6]


In [1]:
# Import necessary libraries
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Load the iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# Split the data into training and testing sets (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a Random Forest classifier
clf = RandomForestClassifier(n_estimators=100)

# Train the model
clf.fit(X_train, y_train)

# Make predictions on the test data
y_pred = clf.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")


Accuracy: 100.00%


In [2]:
a=22
print(a)

22


In [3]:
type(a)

int

In [4]:
c=12
d="string"
d=str(c)+d
d

'12string'

In [5]:
c

12

In [6]:
type(c)

int

In [7]:
d

'12string'

In [8]:
type(d)

str

In [9]:
e= [1,2,3,"ai","ml"]
e

[1, 2, 3, 'ai', 'ml']

In [10]:
e

[1, 2, 3, 'ai', 'ml']

In [11]:
type(e)

list

In [12]:
f=(1,2,3,5,"ai")
f

(1, 2, 3, 5, 'ai')

In [13]:
type(f)

tuple

In [14]:
f

(1, 2, 3, 5, 'ai')

In [15]:
f

(1, 2, 3, 5, 'ai')

In [2]:
a=int(input("enter the number"))
a
if(a>4):
    print("variable is greater")
else:
    print("variable is not greater")

enter the number 6


variable is greater


In [17]:
if(a>4):
    print("variable is greater")

In [ ]:
#if else statements


In [14]:
cohort_attendence = 70


In [15]:
if cohort_attendence <=60:
    print("you won't be certified")
    print("you won't be eligible for placements")

elif 61<= cohort_attendence <=75:
    print("you will be partially certified")

else:
    print("you will be certified")
    print("you will be eligible for placements assistance")

you will be partially certified


In [16]:
attendance_values= [55,67,80,92]


In [17]:
for attendance in attendance_values:
    status = "certified" if attendance >=75 else "not certified"
    print(f"Attendance: {attendance}%, status: {status}")

Attendance: 55%, status: not certified
Attendance: 67%, status: not certified
Attendance: 80%, status: certified
Attendance: 92%, status: certified


In [19]:
friends  = ["vansh","chayank"]
for friend in friends:
    print(friend)

vansh
chayank


In [21]:
for x in range(11):
    print(x*2)

0
2
4
6
8
10
12
14
16
18
20


In [23]:
for i in range(14):
    print(i*2)

0
2
4
6
8
10
12
14
16
18
20
22
24
26


In [28]:
for x in range(11):
    print(x)
    
         
    

0
1
2
3
4
5
6
7
8
9
10


In [31]:
for x in range(100):
    if x == 20:
        break
    print(x)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [33]:
for x in range(100):
    if x == 20:
        continue
    print(x)    

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [34]:
for a in "cohort24":
    print(a)


c
o
h
o
r
t
2
4


In [36]:
for x in range(2):
    for a in range(3):
        print(x, a)

0 0
0 1
0 2
1 0
1 1
1 2


In [1]:
# Given lists
student_names = ["Mr. A", "Mr. B", "Mr. C", "Mr. D", "Mr. E"]
attendance = [85, 60, 72, 90, 55]  # Percentage of classes attended
scores = [88, 45, 67, 92, 59]  # Exam scores out of 100

# Iterating through each student’s data
for i in range(len(student_names)):
    student_name = student_names[i]
    student_attendance = attendance[i]
    student_score = scores[i]

    # Check if attendance is below 60%
    if student_attendance < 60:
        print(f"{student_name} needs to improve attendance.")
        
        # If both attendance is below 60% and score below 50, terminate the program
        if student_score < 50:
            print("Program terminated due to low performance.")
            break
        continue  # Skip score evaluation if attendance is low
    
    # Evaluating exam score and determining the grade
    if student_score >= 90:
        grade = "A"
        feedback = "Excellent performance!"
    elif 75 <= student_score < 90:
        grade = "B"
        feedback = None  # No special feedback for grade B
    elif 60 <= student_score < 75:
        grade = "C"
        feedback = None  # No special feedback for grade C
    else:
        grade = "D"
        feedback = "Needs significant improvement!"

    # Printing the student's name, attendance, score, and grade
    print(f"Student: {student_name}")
    print(f"Attendance: {student_attendance}%")
    print(f"Score: {student_score}")
    print(f"Grade: {grade}")
    
    # Printing additional feedback if any
    if feedback:
        print(feedback)
    
    print()  # Adding a blank line for better readability between student outputs


Student: Mr. A
Attendance: 85%
Score: 88
Grade: B

Student: Mr. B
Attendance: 60%
Score: 45
Grade: D
Needs significant improvement!

Student: Mr. C
Attendance: 72%
Score: 67
Grade: C

Student: Mr. D
Attendance: 90%
Score: 92
Grade: A
Excellent performance!

Mr. E needs to improve attendance.
